from payroll import Payroll
empl1= Payroll("Aaron Mwanzia","A0123456789W",29094964,220000,0,0)
print("Name is: ", empl1.emp_name)
print("KRA PIN is: ", empl1.KRA_PIN)
print("ID number is: ", empl1.id_number)
print("Basic salary: ", empl1.basic_salary)
print("Allowances: ", empl1.allowances)
print("Other deductions: ", empl1.other_deductions)
# print("Pension: ", empl1.pension)
print("Gross Salary: ", empl1.gross_salary)
print("NSSF Deductions: ", empl1.nssf_deductions)
print("Taxable Income: 	{:.2f}".format(empl1.taxable_income))
print("NHIF Deductions: ", empl1.nhif_deductions)
print("PAYE: {:.2f}".format(empl1.payee))
print("Total deductions: {:.2f}".format(empl1.total_deductions))
print("Net Salary: {:.2f}".format(empl1.net_salary))
